server:
  port: 8085

spring:
  thymeleaf:
    enabled: true
    mode: "HTML5"
    prefix: "classpath:templates/"
    suffix: ".html"
    encoding: "UTF-8"
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/payments
    jpa:
      show-sql: true
      format-sql: true


logging:
  level:
    root: info
    com.example.mvcproject: debug
